services:
  mulaflow:
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_IMAGE}:${DEPLOYMENT_TAG}
    restart: unless-stopped
    environment:
      - DD_ENV=staging
      - SPRING_PROFILES_ACTIVE=staging
      - SPRING_CONFIG_IMPORT=file:/run/secrets/application-secrets.properties
      - SPRING_DATASOURCE_URL=${STAGING_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${STAGING_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${STAGING_DB_PASSWORD}
      - DD_API_KEY=${DATADOG_API_KEY}
    secrets:
      - source: app_secrets
        target: /run/secrets/application-secrets.properties
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

secrets:
  app_secrets:
    file: ./secrets/application-secrets.properties
