services:
  mulaflow:
    image: ${DOCKER_HUB_USERNAME}
    restart: unless-stopped
    # build: 
    #   context: ../../..
    #   args:
    #     - SPRING_PROFILES_ACTIVE=staging
    environment:
      - DD_ENV=local
      - SPRING_CONFIG_IMPORT=file:/run/secrets/application-secrets.properties
      - SPRING_DATASOURCE_URL=${{ secrets.STAGING_DB_URL }}
      - SPRING_DATASOURCE_USERNAME=${{ secrets.STAGING_DB_USERNAME }}
      - SPRING_DATASOURCE_PASSWORD=${{ secrets.STAGING_DB_PASSWORD }}
    secrets:
      - source: app_secrets
        target: /run/secrets/application-secrets.properties
      - source: datadog_api_key
        target: /run/secrets/datadog_api_key.txt
    ports:
      - "8080:8080"

secrets:
  app_secrets:
    file: ./secrets/application-secrets.properties
  db_password:
    file: ./secrets/db_password.txt
  datadog_api_key:
    file: ./secrets/datadog_api_key.txt
  

volumes:
  pgdata:
