# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      security-events: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
        STAGING_DB_USERNAME: ${{ secrets.STAGING_DB_USERNAME }}
        STAGING_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
        DEPLOYMENT_TAG: ${{ env.DEPLOYMENT_TAG }}
      run: STAGING_DB_URL=${{ secrets.STAGING_DB_URL }} STAGING_DB_USERNAME=${{ secrets.STAGING_DB_USERNAME }} STAGING_DB_PASSWORD=${{ secrets.STAGING_DB_PASSWORD }} ENVIROMENT=${{ secrets.ENVIROMENT }} DEV_TOOLS=${{ secrets.DEV_TOOLS }} LOG_LEVEL=${{ secrets.LOG_LEVEL }} JWT_SECRET=${{ secrets.JWT_SECRET }} JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} JWT_REFRESH_EXPIRATION=${{ secrets.JWT_REFRESH_EXPIRATION }} EMAIL_HOST=${{ secrets.EMAIL_HOST }} EMAIL_PORT=${{ secrets.EMAIL_PORT }} EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} EMAIL_PROTOCOL=${{ secrets.EMAIL_PROTOCOL }} EMAIL_PROPERTIES_AUTH=${{ secrets.EMAIL_PROPERTIES_AUTH }} EMAIL_PROPERTIES_STARTTLS_ENABLE=${{ secrets.EMAIL_PROPERTIES_STARTTLS_ENABLE }} mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
