name: Build & Deploy (Staging)

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

env:
  DOCKER_IMAGE: mulaflow
  DOCKER_COMPOSE_FILE: docker/compose/staging/docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:staging \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }} .
        
      - name: Push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:staging
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update \
          && curl -SL https://github.com/docker/compose/releases/download/v2.35.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose \
          && chmod +x /usr/local/bin/docker-compose
      
      - name: Deploy to Staging
        env:
          STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
          STAGING_DB_USERNAME: ${{ secrets.STAGING_DB_USERNAME }}
          STAGING_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          DEPLOYMENT_TAG: staging

        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d
