name: Build & Deploy (Staging)

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

env:
  DOCKER_IMAGE: mulaflow
  DEPLOYMENT_TAG: staging
  DOCKER_COMPOSE_FILE: docker/compose/staging/docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:staging \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }} .
        
      - name: Push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DEPLOYMENT_TAG }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  # publish:
  #   needs: build
  #   uses: gh-actions-workflows/docker-workflows/.github/workflows/docker-publish.yaml@master
  #   with:
  #     app_name: 'mulaflow'
  #     docker_hub_user: ${{ secrets.DOCKER_HUB_USERNAME }}
  #     docker_hub_password: ${{ secrets.DOCKER_HUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Create secrets directory
        run: |
          mkdir -p docker/compose/staging/secrets
          echo "Creating application-secrets.properties with environment variables"
          cat <<EOF > docker/compose/staging/secrets/application-secrets.properties
          # Database configuration
          spring.datasource.url=${STAGING_DB_URL}
          spring.datasource.username=${STAGING_DB_USERNAME}
          spring.datasource.password=${STAGING_DB_PASSWORD}
          
          # Other secrets
          datadog.api.key=${DATADOG_API_KEY}
          EOF
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update \
          && curl -SL https://github.com/docker/compose/releases/download/v2.35.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose \
          && chmod +x /usr/local/bin/docker-compose
      
      - name: Deploy to Staging
        env:
          STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
          STAGING_DB_USERNAME: ${{ secrets.STAGING_DB_USERNAME }}
          STAGING_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          DEPLOYMENT_TAG: ${{ env.DEPLOYMENT_TAG }}

        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d

      # - name: Trigger Render Deployment
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: Bearer ${{ secrets.RENDER_STAGING_TOKEN }}" \
      #       -H "Accept: application/json" \
      #       -H "Content-Type: application/json" \
      #       "https://api.render.com/v1/services/${{ secrets.RENDER_STAGING_SERVICE_ID }}/deploys" \
      #       -d '{
      #         "clearCache": "clear"
      #       }'

      # - name: Deploy to Render
      #   uses: gh-actions-workflows/deploy-docker-render@v1.1
      #   with:
      #     deploy-hook: ${{ secrets.RENDER_STAGING_DEPLOY_HOOK }}
      #     render-api-key: ${{ secrets.RENDER_STAGING_TOKEN }}
      #     wait-for-deployment: true


  deploy-to-render:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "${{ secrets.RENDER_STAGING_SERVICE_ID }}",
              "image": "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DEPLOYMENT_TAG }}"
            }' \
            "https://api.render.com/v1/services/${{ secrets.RENDER_STAGING_SERVICE_ID }}/deploys"
          # ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DEPLOYMENT_TAG }}

        # uses: render-oss/deploy-docker-render@v1
        # with:
        #   service-id: ${{ secrets.RENDER_STAGING_SERVICE_ID }}
        #   docker-image: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DEPLOYMENT_TAG }}
        #   render-api-key: ${{ secrets.RENDER_STAGING_TOKEN }} 
        #   clear-cache: clear 
        #   wait-for-deployment: true




  # deploy-to-render:
  #   needs: publish
  #   runs-on: ubuntu-latest
  #   environment: staging
  #   steps:
  #     - uses: actions/checkout@v4
      


          # api_key: ${{ secrets.RENDER_STAGING_TOKEN }}
          # service_id: ${{ secrets.RENDER_STAGING_SERVICE_ID }}
          # # docker-image: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DEPLOYMENT_TAG }}
          # clear_cache: true
          # wait_deploy: true
          # github_deployment: true
          # deployment_environment: 'staging'
          # github_token: ${{ secrets.GITHUB_TOKEN }}
